tap "homebrew/bundle"
tap "oven-sh/bun"
tap "xcodesorg/made"
brew "libssh2"
brew "aria2"
brew "automake"
brew "libtool"
brew "asdf"
brew "cmake"
brew "gh"
brew "zstd"
brew "ghostscript"
brew "go"
brew "icu4c"
brew "jq"
brew "libiconv"
brew "llvm@16"
brew "mas"
brew "ninja"
brew "rustup"
brew "sccache"
brew "tree"
brew "oven-sh/bun/bun"
brew "xcodesorg/made/xcodes"
cask "1password"
cask "1password-cli"
cask "android-studio"
cask "appcleaner"
cask "brave-browser"
cask "discord"
cask "firefox"
cask "fork"
cask "google-cloud-sdk"
cask "messenger"
cask "monitorcontrol"
cask "notion"
cask "slack"
cask "visual-studio-code"
cask "warp"
cask "zoom"
mas "Keynote", id: 409183694
mas "NordVPN", id: 905953485
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
